<a href="https://colab.research.google.com/github/Virvivek007/House_price_Data_Analytics/blob/main/House_Price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Python Module

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [7]:
#load dataset
train_data_path = r"/content/sample_data/california_housing_test.csv"
test_data_path  = r"/content/sample_data/california_housing_train.csv"

df_train = pd.read_csv(train_data_path)
df_test = pd.read_csv(test_data_path )

print("Shape of df_train:",df_train.shape)
print("Shape of df_test:",df_test.shape)

Shape of df_train: (3000, 9)
Shape of df_test: (17000, 9)

In [9]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

# Display first 5 Rows

In [10]:
df_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [11]:
df_test.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [12]:
df = pd.concat([df_train,df_test])
print("Shape of Integrated Data/ DF: ",df.shape)

Shape of Integrated Data/ DF:  (20000, 9)

In [13]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

# Display Last 5 Rows

In [14]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

# Data Information

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20000 non-null  float64
 1   latitude            20000 non-null  float64
 2   housing_median_age  20000 non-null  float64
 3   total_rooms         20000 non-null  float64
 4   total_bedrooms      20000 non-null  float64
 5   population          20000 non-null  float64
 6   households          20000 non-null  float64
 7   median_income       20000 non-null  float64
 8   median_house_value  20000 non-null  float64
dtypes: float64(9)
memory usage: 1.5 MB

In [16]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,-119.566172,35.626750,28.627750,2637.051550,537.991800,1425.557650,499.525450,3.872132,207082.716750
std,2.003609,2.136141,12.582229,2176.314757,420.631119,1131.048487,381.729517,1.900356,115557.055856
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1451.000000,296.000000,788.000000,280.000000,2.562500,119800.000000
50%,-118.490000,34.250000,29.000000,2126.000000,434.000000,1166.000000,409.000000,3.536000,179800.000000
75%,-118.000000,37.710000,37.000000,3149.000000,647.000000,1724.000000,604.000000,4.745325,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

# Step 2 — Data Quality Assessment

In [17]:
print(f"Shape: {df.shape}")
print(f"\nMissing Values:\n{df.isnull().sum()[df.isnull().sum() > 0]}")
print(f"\nDuplicates: {df.duplicated().sum()}")
print(f"\nData Types:\n{df.dtypes}")
print(f"\nStatistical Summary:\n{df.describe()}")

Shape: (20000, 9)

Missing Values:
Series([], dtype: int64)

Duplicates: 0

Data Types:
longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

Statistical Summary:
          longitude      latitude  housing_median_age   total_rooms  \
count  20000.000000  20000.000000        20000.000000  20000.000000
mean    -119.566172     35.626750           28.627750   2637.051550
std        2.003609      2.136141           12.582229   2176.314757
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.790000     33.930000           18.000000   1451.000000
50%     -118.490000     34.250000           29.000000   2126.000000
75%     -118.000000     37.710000           37.000000   3149.000000
max     -114.310000     41.950000           52.000000  37937.000000

       total_bedrooms    population    households  median_income  \
count    20000.000000  20000.000000  20000.000000   20000.000000
mean       537.991800   1425.557650    499.525450       3.872132
std        420.631119   1131.048487    381.729517       1.900356
min          1.000000      3.000000      1.000000       0.499900
25%        296.000000    788.000000    280.000000       2.562500
50%        434.000000   1166.000000    409.000000       3.536000
75%        647.000000   1724.000000    604.000000       4.745325
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        20000.000000
mean        207082.716750
std         115557.055856
min          14999.000000
25%         119800.000000
50%         179800.000000
75%         265000.000000
max         500001.000000

# Step 3 — Data Cleaning & Transformation

In [20]:
# Numerical columns — fill with median
num_cols = ['longitude', 'latitude', 'population']
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipykernel_802/3924557117.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)